// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDmE5uAZIBAY-KeU16HO7jGnZUADzu1RgQ',
    appId: '1:187974393590:android:e8d0577bf472bef0b596d7',
    messagingSenderId: '187974393590',
    projectId: 'taxi-app-e9b29',
    storageBucket: 'taxi-app-e9b29.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBppU6EXH0IoJk7ncxTBzYz5GfH9GLNLlU',
    appId: '1:187974393590:ios:a6117c9719f279e0b596d7',
    messagingSenderId: '187974393590',
    projectId: 'taxi-app-e9b29',
    storageBucket: 'taxi-app-e9b29.appspot.com',
    androidClientId: '187974393590-h2f3o66adcqm8vnma9q9a33odohjnjst.apps.googleusercontent.com',
    iosClientId: '187974393590-pti994p5ivn513fjeb4n4mg3viobbd9v.apps.googleusercontent.com',
    iosBundleId: 'com.example.taxiApp',
  );

}